# Generated by Django 3.0.3 on 2020-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.TextField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
