# Generated by Django 3.0.3 on 2020-03-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='things_i_love',
            new_name='things_loved',
        ),
    ]
