# Generated by Django 3.0.3 on 2020-03-30 14:52

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=90)),
                ('category', models.CharField(choices=[('FRENCH', 'French'), ('ITALIAN', 'Italian'), ('PERUVIAN', 'Peruvian'), ('CHINESE', 'Chinese'), ('JAPANESE', 'Japanese'), ('AMERICAN', 'American')], default='FRENCH', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street', models.CharField(max_length=270)),
                ('city', models.CharField(max_length=90)),
                ('zip', models.CharField(max_length=45)),
                ('website', models.CharField(max_length=90)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.CharField(max_length=90)),
                ('opening_hours', models.CharField(max_length=45)),
                ('price_level', models.CharField(choices=[('1', 'Inexpensive'), ('2', 'Moderately expensive'), ('3', 'Expensive'), ('4', 'Very expensive')], default='2', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
