# Generated by Django 3.0.3 on 2020-03-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='review content')),
                ('rating', models.IntegerField(choices=[('1', 'Could do better'), ('2', 'Experience is ok'), ('3', 'Expect a good lunch'), ('4', 'Great restaurant'), ('5', 'WOW experience')], verbose_name='review rating')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('idRestaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Review_to_Restaurant', to='restaurants.Restaurant')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Review_to_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
    ]
