# Generated by Django 3.0.3 on 2020-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star, could do better'), (2, '2 stars, experience is ok'), (3, '3 stars, expect a good lunch'), (4, '4 stars, great restaurant'), (5, '5 stars, WOW experience')], verbose_name='review rating'),
        ),
    ]
