# Generated by Django 3.0.3 on 2020-03-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20200331_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='comment content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('idComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_Comment_to_Comment', to='reviews.Comment')),
                ('idReview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_Comment_to_Review', to='reviews.Review')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Comment_to_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_Like_to_Comment', to='reviews.Comment')),
                ('idReview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_Like_to_Review', to='reviews.Review')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Like_to_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
