# Generated by Django 3.0.3 on 2020-04-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200401_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id_restaurant',
            new_name='idRestaurant',
        ),
    ]
