# Generated by Django 3.0.3 on 2020-04-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200401_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='idRestaurant',
            new_name='id_restaurant',
        ),
    ]
